---
# copyright Utrecht University

- name: Find out if default-0 metadata schema is installed
  become_user: "{{ irods_service_account }}"
  become: yes
  command: 'ils /{{ irods_zone }}/yoda/schemas/default-0/{{ item }}'
  ignore_errors: True
  register: installed_defaults
  changed_when: False
  with_items:
    - metadata.json
    - uischema.json
    - research.xsd
    - vault.xsd
    - avu.xsl
    - datacite.xsl
    - landingpage.xsl


- name: Ensure default-0 metadata schema is installed
  become_user: "{{ irods_service_account }}"
  become: yes
  command: >
    irule -F /etc/irods/irods-ruleset-research/tools/install-metadata-schema.r
    '*resc="{{ irods_default_resc }}"'
    '*src="/etc/irods/irods-ruleset-research/tools/schemas/"'
    '*schema="default-0"'
    '*category="default-0"'
    '*update={{ update_schemas }}'
  register: install_default_0_xml_for_metadata
  when: (update_schemas == 1) or
        (installed_defaults|json_query('results[*].stderr')|join(' ') is search('does not exist'))
  changed_when: install_default_0_xml_for_metadata.stdout is search('(Installed|Updated)')


- name: List installed or updated schemas, formelements or stylesheets
  become_user: "{{ irods_service_account }}"
  become: yes
  debug:
    var: item
  when: item is search('(Installed|Updated)')
  with_items: "{{ install_default_0_xml_for_metadata.stdout_lines|default('Script did not run') }}"

- name: Find out if default-1 metadata schema is installed
  become_user: "{{ irods_service_account }}"
  become: yes
  command: 'ils /{{ irods_zone }}/yoda/schemas/default-1/{{ item }}'
  ignore_errors: True
  register: installed_defaults
  changed_when: False
  with_items:
    - metadata.json
    - uischema.json
    - research.xsd
    - vault.xsd
    - avu.xsl
    - datacite.xsl
    - landingpage.xsl


- name: Ensure default-1 metadata schema is installed
  become_user: "{{ irods_service_account }}"
  become: yes
  command: >
    irule -F /etc/irods/irods-ruleset-research/tools/install-metadata-schema.r
    '*resc="{{ irods_default_resc }}"'
    '*src="/etc/irods/irods-ruleset-research/tools/schemas/"'
    '*schema="default-1"'
    '*category="default-1"'
    '*update={{ update_schemas }}'
  register: install_default_1_xml_for_metadata
  when: (update_schemas == 1) or
        (installed_defaults|json_query('results[*].stderr')|join(' ') is search('does not exist'))
  changed_when: install_default_1_xml_for_metadata.stdout is search('(Installed|Updated)')


- name: List installed or updated schemas, formelements or stylesheets
  become_user: "{{ irods_service_account }}"
  become: yes
  debug:
    var: item
  when: item is search('(Installed|Updated)')
  with_items: "{{ install_default_1_xml_for_metadata.stdout_lines|default('Script did not run') }}"
